name: Run clang-format Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './CPP_flight_computer_program'
        exclude: './CPP_flight_computer_program/lib'
        extensions: 'h,cpp,c'
        clangFormatVersion: 15
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
          default_author: github_actions
